notifications:
  email: false

language: node_js

node_js:
  - '0.10'

before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick graphicsmagick libcairo2-dev

before_script:
  - "cd test/site && ../../node_modules/.bin/bower install && cd ../../"
  - "curl -O http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar"
  - "java -jar selenium-server-standalone-2.41.0.jar -host 127.0.0.1 -port 4444 &"
  - "python -m SimpleHTTPServer 8080 &"

script: "npm test"