notifications:
  email: false

language: node_js

node_js:
  - '0.10'

before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick graphicsmagick libcairo2-dev jscoverage

before_script:
  - "cd test/site && ../../node_modules/.bin/bower install && cd ../../"
  - "curl -O http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar"
  - "java -jar selenium-server-standalone-2.41.0.jar > /dev/null 2>&1 &"
  - "python -m SimpleHTTPServer 8080 > /dev/null 2>&1 &"
  - "jscoverage lib lib-cov"

script: "WEBDRIVERCSS_COV=1 ./node_modules/.bin/mocha mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js"